Now the client looks at a pool of IP addresses corresponding to checkip.dyndns.com. Also fixed the invocation of the is_valid_ip function.

diff --git a/ddns-client b/ddns-client
--- a/ddns-client
+++ b/ddns-client
@@ -133,7 +133,7 @@ while [ true ]; do
     logger -p "user.info" -t "$logger_proginfo" \
         "checking registered ip... $registered_ip"
 
-    if [ ! "is_valid_ip $registered_ip" ]; then
+    if ! is_valid_ip "$registered_ip"; then
         logger -p "user.error" -t "$logger_proginfo" \
             "registered IP is invalid. I will retry after 1 min."
         sleep 60
@@ -141,17 +141,23 @@ while [ true ]; do
     fi
 
     # Retrieve the current IP
-    # Use absolute address to avoid DNS problems.
-    # This is the address of `checkip.dyndns.com'.
-    current_ip=$(wget -nv -O - \
-        'http://208.78.70.70' 2> /dev/null | \
-        grep -o -e '\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}')
-    logger -p "user.info" -t "$logger_proginfo" \
-        "checking current ip... $current_ip"
+    # Use absolute address to avoid DNS failures.
+    # This is the address pool of `checkip.dyndns.com'.
+    check_srv_pool="204.13.248.70 208.78.69.70 91.198.22.70"
+    for srv_ip in $check_srv_pool; do
+	current_ip=$(wget --tries 4 --timeout 3 -nv -O - \
+            "http://$srv_ip" 2> /dev/null | \
+            grep -o -e '\([[:digit:]]\{1,3\}\.\)\{3\}[[:digit:]]\{1,3\}')
+	logger -p "user.info" -t "$logger_proginfo" \
+            "checking current IP from server $srv_ip... $current_ip"
+	if is_valid_ip "$current_ip"; then
+	    break
+	fi
+    done
 
-    if [ ! "is_valid_ip $current_ip" ]; then
+    if ! is_valid_ip "$current_ip"; then
         logger -p "user.error" -t "$logger_proginfo" \
-            "current IP is invalid. I will retry after 1 min."
+            "could not retrieve the current IP address; i will retry after 1 min."
         sleep 60
         continue
     fi
